## Running: C:\Users\eegadmin\Desktop\Psychopy experiment Kaylee - Copy\LangExperimentstress_lastrun.py ##
0xFF
## Running: C:\Users\eegadmin\Desktop\Psychopy experiment Kaylee - Copy\LangExperimentstress_lastrun.py ##
Exception in thread Thread-2 (ReadThread):
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\PsychoPy\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eegadmin\Desktop\Psychopy experiment Kaylee - Copy\LangExperimentstress_lastrun.py", line 49, in ReadThread
    if port.in_waiting > 0:
  File "C:\Users\eegadmin\AppData\Roaming\psychopy3\packages\Python310\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'A device attached to the system is not functioning.', None, 31))
Traceback (most recent call last):
  File "C:\Users\eegadmin\Desktop\Psychopy experiment Kaylee - Copy\LangExperimentstress_lastrun.py", line 1506, in <module>
    if expInfo['version'] == '1':
KeyError: 'version'
################ Experiment ended with exit code 1 [pid:16948] #################
Exception in thread Thread-2 (ReadThread):
Traceback (most recent call last):
  File "C:\Program Files\PsychoPy\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\PsychoPy\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eegadmin\Desktop\Psychopy experiment Kaylee - Copy\LangExperimentstress_lastrun.py", line 49, in ReadThread
    if port.in_waiting > 0:
  File "C:\Users\eegadmin\AppData\Roaming\psychopy3\packages\Python310\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'A device attached to the system is not functioning.', None, 31))
################# Experiment ended with exit code 0 [pid:3104] #################
